version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node:lts

jobs:
  test:
    executor: my-custom-executor
    steps:
      - checkout
      - run:
          name: 'Install'
          command: npm ci
      - run:
          name: 'Test'
          command: npm run e2e
  build:
    executor: my-custom-executor
    steps:
      - checkout
      - run:
          name: 'Install'
          command: npm ci
      - run:
          name: 'Build'
          command: npm run build

workflows:
  my-custom-workflow:
    jobs:
      - build
      - test
