version: 2.1
executors:
  node-lts:
    docker:
      - image: cimg/node:lts

jobs:
  install:
    executor: node-lts
    steps:
      - checkout
      - run:
          name: 'Install'
          command: npm ci
      - persist_to_workspace:
          root: ./
          paths:
            - ./*
  build:
    executor: node-lts
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: 'Build'
          command: npm run build
  unit:
    executor: node-lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Unit Tests'
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
      - store_artifacts:
          path: coverage
  e2e:
    executor: node-lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'E2E Tests'
          command: npm run e2e
  version:
    executor: node-lts
    steps:
      - attach_workspace:
          at: .
      - run:
          command: echo "" > old_version && echo 1.3.0 > new_version
      # - run:
      #     name: 'Version'
      #     command: npx semantic-release -d
      - persist_to_workspace:
          root: ./
          paths:
            - old_version
            - new_version
  deploy:
    executor: node-lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'Deploy'
          command: |
            OLD_VERSION=$(cat old_version)
            NEW_VERSION=$(cat new_version)
            echo "From ${OLD_VERSION} to ${NEW_VERSION}"
            if [[ -z "${NEW_VERSION}" ]]; then
              echo "No new version. Skip deploy."
            else
              echo "Deploying v${NEW_VERSION}"
              ssh -oStrictHostKeyChecking=no -v $USER@$IP_ADDRESS ". /home/${USER}/.nvm/nvm.sh; ./scripts/deploy-foxcasts-api.sh v${NEW_VERSION}"
            fi

workflows:
  build-and-test:
    jobs:
      - install
      # - build:
      #     requires:
      #       - install
      # - unit:
      #     requires:
      #       - install
      # - e2e:
      #     requires:
      #       - install
      - version:
          context: github-versioning
          requires:
            - install
          # requires:
          #   - build
          #   - unit
          #   - e2e
          filters:
            branches:
              only:
                - main
                - deploy
      - deploy:
          context: digital-ocean-deploy
          requires:
            - version
          filters:
            branches:
              only:
                - main
                - deploy
