version: 2.1
executors:
  node-lts:
    docker:
      - image: cimg/node:lts

jobs:
  build:
    executor: node-lts
    steps:
      - checkout
      - run:
          name: 'Install'
          command: npm ci
      # - run:
      #     name: 'Build'
      #     command: npm run build
      - run: mkdir -p workspace
      - persist_to_workspace:
          root: workspace
          paths:
            - .
      - run:
          name: 'List'
          command: ls -la
  test:
    executor: node-lts
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: 'List'
          command: ls -la
      # - run:
      #     name: 'E2E Tests'
      #     command: npm run e2e
      # - run:
      #     name: 'Unit Tests'
      #     command: npm run test:ci
      #     environment:
      #       JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      # - store_test_results:
      #     path: ./reports/junit/
      # - store_artifacts:
      #     path: ./reports/junit
      # - store_artifacts:
      #     path: coverage
  version:
    executor: node-lts
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: 'List'
          command: ls -la
      - run:
          name: 'Version'
          # command: npx semantic-release -d
          command: echo "Perform versioning"
  deploy:
    executor: node-lts
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: 'List'
          command: ls -la
      - run:
          name: 'Deploy'
          command: echo "Perform deploy now"

workflows:
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - version:
          context: github-versioning
          requires:
            - build
            - test
      - deploy:
          requires:
            - version
