version: 2.1
executors:
  node-lts:
    docker:
      - image: cimg/node:lts

jobs:
  build:
    executor: node-lts
    steps:
      - checkout
      - run:
          name: 'Install'
          command: npm ci
      - run:
          name: 'Build'
          command: npm run build
      - persist_to_workspace:
          root: ./
          paths:
            - ./*
      - run:
          name: 'List'
          command: ls -la
  unit:
    executor: node-lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'List'
          command: ls -la
      - run:
          name: 'Unit Tests'
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
      - store_artifacts:
          path: coverage
  e2e:
    executor: node-lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'List'
          command: ls -la
      - run:
          name: 'E2E Tests'
          command: npm run e2e
  version:
    executor: node-lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'List'
          command: ls -la
      - run:
          name: 'Version'
          # command: npx semantic-release -d
          command: echo "Perform versioning"
  deploy:
    executor: node-lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: 'List'
          command: ls -la
      - run:
          name: 'Deploy'
          command: echo "Perform deploy now"

workflows:
  build-and-test:
    jobs:
      - build
      - unit:
          requires:
            - build
      - e2e:
          requires:
            - build
      - version:
          context: github-versioning
          requires:
            - unit
            - e2e
      - deploy:
          requires:
            - version
